### ISSUE TITLE
Instapaper/Readability Compatibility

### ISSUE THREAD

**Issue by nullicorn** [idan/gistio#16]
Considering the fact that this is for reading writings rather than codes, I think it makes sense to make it compatible with Instapaper and other services similar to it.

Also the <title> element should be the description rather than gist.io#.

**Comment by Potherca** [comment]
<kbd>@idan ✔️ Issue can be closed.</kbd>

Not sure about Instapaper, but the current use of `<article>`, `<header>` and `<footer>`, combined with the Markdown rendering, should be enough for even a mediocre App to understand, let alone a decent one. 

There is also already a dedicated ticket for the `<title>`: https://github.com/idan/gistio/issues/43
