### ISSUE TITLE
not loading if gists filename has an umlaut

### ISSUE THREAD

**Issue by almereyda** [idan/gistio#62]
hi,

just found that gist.io would not load any .md files that have an umlaut.
## not working

http://gist.io/7162358
https://gist.github.com/almereyda/7162358
## working

http://gist.io/7162370
https://gist.github.com/almereyda/7162370

**Comment by Potherca** [comment]
<kbd>@idan ✔️ Issue can be closed.</kbd>

Working URLs:

- <del>http://gist.io/7162358</del>
   ➡️ https://gist.io/@almereyda/7162358

- <del>http://gist.io/7162370</del>
   ➡️ https://gist.io/@almereyda/7162370

Also, this is a duplicate of https://github.com/idan/gistio/issues/59

**Comment by almereyda** [comment]
Then, actually, this is not an issue, since as of https://gist.io/ per today, the

`gist.io/<Gist ID>` short cut does not seem to be officially supported.
