### ISSUE TITLE
no joy - bookmarklet doesn't work "Not Found"

### ISSUE THREAD

**Issue by tedstrauss** [idan/gistio#73]
https://gist.github.com/tedstrauss/06e9cef827fcfda6392d

**Comment by stuartcw** [comment]
Me too.. is gistio still being maintained? 

https://gist.github.com/stuartcw/3bcf2b3d4896b8483286

**Comment by Potherca** [comment]
<kbd>@idan  ✔️ Issue can be closed.</kbd>

Working URLS:
- https://gist.io/@tedstrauss/06e9cef827fcfda6392d
- https://gist.io/@stuartcw/3bcf2b3d4896b8483286

**Comment by ted-strauss-K1** [comment]
nice
