### ISSUE TITLE
Announcement: gist.io is dead

### ISSUE THREAD

**Issue by nilbus** [idan/gistio#74]
http://draft.sx
`http://draft.sx/<public_gist_id>`

Thanks to @x3ro for putting this together!

---

@idan If you come back and start maintaining this project again, please close this issue. We'd welcome you back along with gist.io!

**Comment by fuzzy76** [comment]
Should really have been on the frontpage of gist.io

**Comment by fuzzy76** [comment]
And now draft.sx shut down :-/

**Comment by x3ro** [comment]
Yeah, sorry about that. I'm happy with giving away the domain name to someone who would like to host the project though, and help them set it up even.

**Comment by nilbus** [comment]
@x3ro Yes, let's talk! I'll follow up by email.

**Comment by nilbus** [comment]
FYI, I did not end up taking over the domain.

**Comment by fuzzy76** [comment]
I was considering doing a pure javascript alternative which could be hosted on github pages. It would require me to find some free time during christmas. Can't promise anything though.

**Comment by wimpunk** [comment]
And now draft.sx is dead to.... Any other alternative?

**Comment by fomightez** [comment]
@ wimpunk Only one I know of that is still running is [roughdraft.io](http://www.roughdraft.io/).

**Comment by wimpunk** [comment]
@fomightez Thanks!

**Comment by sntran** [comment]
I was working on something similar to this, and intend to pick it back up. I would like to see if I can take over the `gist.io` domain from @idan .

**Comment by shinenelson** [comment]
I'm up for this. @x3ro are you still open to this?

@sntran, I'd like to collaborate with you if you're still up for this.

@fuzzy76 Did you get some time last christmas to hack up a pure-Javascript implementation that we could host on Github Pages?

**Comment by x3ro** [comment]
@shinenelson sure!

**Comment by eyecatchup** [comment]
@fuzzy76 Just stumbled upon your comment and liked the idea of a pure JS implementation to be hosted on GH pages. So I hacked together a few lines. Here's a working draft:

Code: https://github.com/eyecatchup/nicegist
Demo: https://eyecatchup.github.io/nicegist/?id=dab5cf7977008e504213

For now, only supports markdown (not limited to GFM syntax though).

**Comment by eyecatchup** [comment]
I created an issue for feature requests: https://github.com/eyecatchup/nicegist/issues/2

Looking forward to suggestions.

**Comment by eyecatchup** [comment]
@fomightez Could you please update your comment? I moved the repo to an organisation account (for shorter URLs).

Code: https://github.com/nicegist/nicegist.github.io
Demo: https://nicegist.github.io/3382937

Thanks!

**Comment by fuzzy76** [comment]
Any reason requests and bugs shouldn't be posted as individual issues?

**Comment by Potherca** [comment]
Well... whether temporary or not, this project seems to be alive again!

**Comment by idan** [comment]
Have a litte more time nowadays, and hacking on this after a loooong break
:)

**Comment by Potherca** [comment]
Well, kind sir, I for one am _very_ happy for it! 🎉 🎈 

Also, you might now want to close this ticket 😀

Or almost _all_ tickets as they pertain to the pre-react version :trollface:

**Comment by nilbus** [comment]
That’s great news!

I will close this because I can, though I agree, all the others should likely be closed too. :+1:
